using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Platform.Portal.Models;
using Platform.Portal.Models.PBAC;
using Platform.Shared.Constants;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Platform.Portal.Data;

/// <summary>
/// Inizializzatore del database con dati di seed
/// </summary>
public static class DbInitializer
{
    /// <summary>
    /// Inizializza il database e crea utenti, ruoli, permessi atomici e policy PBAC di default
    /// </summary>
    public static async Task Initialize(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager)
    {
        // Applica le migrazioni pending e crea il database se non esiste
        await context.Database.MigrateAsync();

        // Garantisci la creazione delle tabelle PBAC se non ancora create dalle migrazioni
        try
        {
            await context.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""PermissionCatalogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Key"" character varying(150) NOT NULL,
                    ""Area"" character varying(100) NOT NULL,
                    ""Module"" character varying(100) NOT NULL,
                    ""Action"" character varying(50) NOT NULL,
                    ""Description"" character varying(255) NOT NULL
                );");

            await context.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""Policies"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" character varying(100) NOT NULL,
                    ""Description"" character varying(500),
                    ""IsSystemPolicy"" boolean NOT NULL DEFAULT FALSE,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL
                );");

            await context.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""PolicyPermissions"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""PolicyId"" integer NOT NULL REFERENCES ""Policies""(""Id"") ON DELETE CASCADE,
                    ""PermissionCatalogId"" integer NOT NULL REFERENCES ""PermissionCatalogs""(""Id"") ON DELETE CASCADE
                );");

            await context.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""RolePolicyAssignments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""RoleName"" character varying(100) NOT NULL,
                    ""PolicyId"" integer NOT NULL REFERENCES ""Policies""(""Id"") ON DELETE CASCADE,
                    ""CompanyScope"" character varying(100),
                    ""DepartmentScope"" character varying(100),
                    ""AssignedAt"" timestamp with time zone NOT NULL
                );");

            await context.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""UserPolicyAssignments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" text NOT NULL REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE,
                    ""PolicyId"" integer NOT NULL REFERENCES ""Policies""(""Id"") ON DELETE CASCADE,
                    ""CompanyScope"" character varying(100),
                    ""DepartmentScope"" character varying(100),
                    ""AssignedAt"" timestamp with time zone NOT NULL
                );");
        }
        catch (Exception ex)
        {
            // Logging in caso di fallimento della creazione manuale
            Console.WriteLine($"Errore creazione tabelle PBAC: {ex.Message}");
        }

        // 1. Inizializza Ruoli Identity
        if (!await roleManager.RoleExistsAsync(PlatformConstants.Roles.Admin))
        {
            await roleManager.CreateAsync(new IdentityRole(PlatformConstants.Roles.Admin));
        }

        if (!await roleManager.RoleExistsAsync(PlatformConstants.Roles.User))
        {
            await roleManager.CreateAsync(new IdentityRole(PlatformConstants.Roles.User));
        }

        if (!await roleManager.RoleExistsAsync("Developer"))
        {
            await roleManager.CreateAsync(new IdentityRole("Developer"));
        }

        if (!await roleManager.RoleExistsAsync("Magazzino"))
        {
            await roleManager.CreateAsync(new IdentityRole("Magazzino"));
        }

        // 2. Inizializza Catalogo Permessi Atomici PBAC
        var defaultPermissions = new List<PermissionCatalog>
        {
            new() { Key = "pharmaself:kiosk:view", Area = "Pharmaself24", Module = "ConfigurationKiosk", Action = "View", Description = "Visualizza schede e checklist Configuration Kiosk" },
            new() { Key = "pharmaself:kiosk:create", Area = "Pharmaself24", Module = "ConfigurationKiosk", Action = "Create", Description = "Crea nuove checklist Configuration Kiosk" },
            new() { Key = "pharmaself:kiosk:edit", Area = "Pharmaself24", Module = "ConfigurationKiosk", Action = "Edit", Description = "Modifica checklist Configuration Kiosk" },
            new() { Key = "pharmaself:kiosk:delete", Area = "Pharmaself24", Module = "ConfigurationKiosk", Action = "Delete", Description = "Elimina checklist Configuration Kiosk" },

            new() { Key = "skript:checklist:view", Area = "SkriptKiosk", Module = "SkriptkioskChecklist", Action = "View", Description = "Visualizza schede e checklist SkriptKiosk" },
            new() { Key = "skript:checklist:create", Area = "SkriptKiosk", Module = "SkriptkioskChecklist", Action = "Create", Description = "Crea nuove checklist SkriptKiosk" },
            new() { Key = "skript:checklist:edit", Area = "SkriptKiosk", Module = "SkriptkioskChecklist", Action = "Edit", Description = "Modifica checklist SkriptKiosk" },
            new() { Key = "skript:checklist:delete", Area = "SkriptKiosk", Module = "SkriptkioskChecklist", Action = "Delete", Description = "Elimina checklist SkriptKiosk" },

            new() { Key = "admin:users:manage", Area = "Admin", Module = "Users", Action = "Manage", Description = "Gestione completa utenti e permessi" }
        };

        foreach (var perm in defaultPermissions)
        {
            if (!await context.PermissionCatalogs.AnyAsync(p => p.Key == perm.Key))
            {
                context.PermissionCatalogs.Add(perm);
            }
        }
        await context.SaveChangesAsync();

        var dbPerms = await context.PermissionCatalogs.ToListAsync();

        // 3. Inizializza Policy PBAC Predefinite
        var adminPolicy = await context.Policies.FirstOrDefaultAsync(p => p.Name == "Amministratore Completo");
        if (adminPolicy == null)
        {
            adminPolicy = new Policy
            {
                Name = "Amministratore Completo",
                Description = "Accesso illimitato a tutti i moduli, azioni e sottoaziende",
                IsSystemPolicy = true,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };
            context.Policies.Add(adminPolicy);
            await context.SaveChangesAsync();

            foreach (var perm in dbPerms)
            {
                context.PolicyPermissions.Add(new PolicyPermission { PolicyId = adminPolicy.Id, PermissionCatalogId = perm.Id });
            }
            await context.SaveChangesAsync();
        }

        var pharmaselfPolicy = await context.Policies.FirstOrDefaultAsync(p => p.Name == "Operatore Pharmaself24");
        if (pharmaselfPolicy == null)
        {
            pharmaselfPolicy = new Policy
            {
                Name = "Operatore Pharmaself24",
                Description = "Gestione completa del modulo Configuration Kiosk per Pharmaself24",
                IsSystemPolicy = false,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };
            context.Policies.Add(pharmaselfPolicy);
            await context.SaveChangesAsync();

            var pharmaPerms = dbPerms.Where(p => p.Area == "Pharmaself24");
            foreach (var perm in pharmaPerms)
            {
                context.PolicyPermissions.Add(new PolicyPermission { PolicyId = pharmaselfPolicy.Id, PermissionCatalogId = perm.Id });
            }
            await context.SaveChangesAsync();
        }

        var skriptPolicy = await context.Policies.FirstOrDefaultAsync(p => p.Name == "Operatore SkriptKiosk");
        if (skriptPolicy == null)
        {
            skriptPolicy = new Policy
            {
                Name = "Operatore SkriptKiosk",
                Description = "Gestione completa del modulo SkriptKiosk Checklist",
                IsSystemPolicy = false,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };
            context.Policies.Add(skriptPolicy);
            await context.SaveChangesAsync();

            var skriptPerms = dbPerms.Where(p => p.Area == "SkriptKiosk");
            foreach (var perm in skriptPerms)
            {
                context.PolicyPermissions.Add(new PolicyPermission { PolicyId = skriptPolicy.Id, PermissionCatalogId = perm.Id });
            }
            await context.SaveChangesAsync();
        }

        var readOnlyPolicy = await context.Policies.FirstOrDefaultAsync(p => p.Name == "Utente Standard Read-Only");
        if (readOnlyPolicy == null)
        {
            readOnlyPolicy = new Policy
            {
                Name = "Utente Standard Read-Only",
                Description = "Permesso di sola lettura su tutti i moduli aziendali",
                IsSystemPolicy = false,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };
            context.Policies.Add(readOnlyPolicy);
            await context.SaveChangesAsync();

            var viewPerms = dbPerms.Where(p => p.Action == "View");
            foreach (var perm in viewPerms)
            {
                context.PolicyPermissions.Add(new PolicyPermission { PolicyId = readOnlyPolicy.Id, PermissionCatalogId = perm.Id });
            }
            await context.SaveChangesAsync();
        }

        // 4. Inizializza Utenti di Test e Assegnazione Policy PBAC
        
        // Developer
        var devUser = await SeedUserAsync(userManager, "developer", "developer@videosystem.it", "Sviluppatore Sistema", "Videosystem01!", "Developer");
        
        // Admin
        var adminUser = await SeedUserAsync(userManager, "admin", "admin@videosystem.it", "Amministratore Sistema", "Admin123!", PlatformConstants.Roles.Admin);
        if (adminUser != null && adminPolicy != null)
        {
            await AssignPolicyToUserIfMissingAsync(context, adminUser.Id, adminPolicy.Id, "ALL", "ALL");
        }

        // Operaio Magazzino 1 (Pharmaself24)
        var pharmaWorker = await SeedUserAsync(userManager, "user_pharmaself", "pharmaself@videosystem.it", "Operaio Magazzino Pharmaself", "User123!", "Magazzino");
        if (pharmaWorker != null && pharmaselfPolicy != null)
        {
            await AssignPolicyToUserIfMissingAsync(context, pharmaWorker.Id, pharmaselfPolicy.Id, "Pharmaself24", "Magazzino");
        }

        // Operaio Magazzino 2 (SkriptKiosk)
        var skriptWorker = await SeedUserAsync(userManager, "user_skript", "skript@videosystem.it", "Operaio Magazzino SkriptKiosk", "User123!", "Magazzino");
        if (skriptWorker != null && skriptPolicy != null)
        {
            await AssignPolicyToUserIfMissingAsync(context, skriptWorker.Id, skriptPolicy.Id, "Skriptkiosk", "Magazzino");
        }

        // Utente Standard (Read-Only)
        var testUser = await SeedUserAsync(userManager, "user", "user@videosystem.it", "Utente Test Standard", "User123!", PlatformConstants.Roles.User);
        if (testUser != null && readOnlyPolicy != null)
        {
            await AssignPolicyToUserIfMissingAsync(context, testUser.Id, readOnlyPolicy.Id, "ALL", "ALL");
        }
    }

    private static async Task<ApplicationUser?> SeedUserAsync(
        UserManager<ApplicationUser> userManager,
        string username,
        string email,
        string fullName,
        string password,
        string role)
    {
        var user = await userManager.FindByNameAsync(username);
        if (user == null)
        {
            user = new ApplicationUser
            {
                UserName = username,
                Email = email,
                EmailConfirmed = true,
                FullName = fullName,
                IsActive = true,
                CreatedAt = DateTime.UtcNow
            };

            var result = await userManager.CreateAsync(user, password);
            if (result.Succeeded)
            {
                await userManager.AddToRoleAsync(user, role);
            }
        }
        else
        {
            if (!await userManager.IsInRoleAsync(user, role))
            {
                await userManager.AddToRoleAsync(user, role);
            }
            var token = await userManager.GeneratePasswordResetTokenAsync(user);
            await userManager.ResetPasswordAsync(user, token, password);
        }
        return user;
    }

    private static async Task AssignPolicyToUserIfMissingAsync(
        ApplicationDbContext context,
        string userId,
        int policyId,
        string companyScope,
        string departmentScope)
    {
        var existing = await context.UserPolicyAssignments.FirstOrDefaultAsync(u => u.UserId == userId && u.PolicyId == policyId);
        if (existing == null)
        {
            context.UserPolicyAssignments.Add(new UserPolicyAssignment
            {
                UserId = userId,
                PolicyId = policyId,
                CompanyScope = companyScope,
                DepartmentScope = departmentScope,
                AssignedAt = DateTime.UtcNow
            });
            await context.SaveChangesAsync();
        }
    }
}
